### ISSUE TITLE
Epic #3: Auth + Profiles

### ISSUE THREAD

**Issue by H-L** [bl-immo/glowing-guacamole#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by antoinegourtay** [comment]
- [ ] Create an identification system
- [ ] Create a registration system
- [ ] Create a simple profile page

**Comment by Tounaze** [comment]
**Product need**
- Ability to create an account with an identifier and a password
- Have access to a profile page with our ID
- Have access to the pages identified and therefore to the creation of the rental file
- Prevent duplicates in terms of identifier in the database
- Verify the password

**V2**
- Can connect with a Google Connect
- Replace the password with touchID, FaceID ...
- Add double anthentification
